### PR TITLE
Support keys with private/experimental hash algorithms

### PR DESCRIPTION
**Pull request by vollkorn1982**
This PR adds private/experimental hash algorithm IDs so keys using these do not fail at importing

### CODE REVIEW

**Comment by vollkorn1982** [comment]
Cleaned this merge request up so it only has my commit in it.

**Comment by J-M0** [comment]
So this will allow keys with private algorithms to be imported, but what happens if you try to do anything else with them? I would imagine there would be more crashes because PGPy doesn't know what these algorithms are.

**Comment by vollkorn1982** [comment]
@J-M0 Thanks for looking at this. I think it's very simple. The OpenPGP standard says those fields can be used for custom algorithms. Custom means here that people who use these know what they are doing and may write their own programs to work with these. Other programs, for example gnupg, ignore these fields silently. Custom algorithms are not meant to be interoperable.

Importing and ignoring these fields is in IMHO the right thing to do because these are standard-conforming keys, which PGPy would not support. And these keys are out there. I have seen them, tried importing them, made this fix and since them successfully used them with PGPy.

If there is a place in the code that allows a user to select these fields I propose PGPy should either remove this possibility to use them or give the user an error message that these fields are not supported. I did not find such a place, though.

**Comment by J-M0** [comment]
I think this has merit, but it probably needs a little more work before it can be merged. Mainly, I don't think just adding to the HashAlgorithm enum is enough. There should at least be checks to make sure PGPy doesn't try to do anything it can't do with  these keys.

How about we merge this into a new branch in PGPy to start working on it?

**Comment by vollkorn1982** [comment]
Making a new branch sounds like a plan. I'll help working on it.

**Pull request merged**
