### PR TITLE
tests/test_03_armor.py: fix syntax

### PR DESCRIPTION
**Pull request by dkg**
Without this fix, there is an immediate failure when running pytest-3.

Signed-off-by: Daniel Kahn Gillmor <dkg@fifthhorseman.net>

### CODE REVIEW

**Comment by dkg** [comment]
this is a fix to the syntax of e163a0cf22735d639ecaaeab4cd6c903acb9a5c5, but i actually don't understand that commit at all -- how is it possibly expected to work (even with the right syntax) with a dynamically-generated creation/expiration date, when the underlying test object is static?

**Comment by dkg** [comment]
@fuhrysteve  can you comment on this?

**Comment by dkg** [comment]
With these changes, `pytest-3` passes all tests on a modern system with python 3.7 and python3-cryptography 2.6.1 (although many warnings remain)

**Comment by fuhrysteve** [comment]
@dkg That commit was awhile ago, but I remember believing at the time that there was something in the tests that were failing due to hard coded (as opposed to relative) dates being too old & expiring or something. Regretfully, it was more of an aggressive / experimental attempt to fix the build at the time rather than a really well thought out & well understood change!

**Comment by dkg** [comment]
@fuhrysteve thanks very much for the followup.  I've done my fair share of aggressive/experimental attempts to "just make it build" so i know where that's coming from :)

In the future, it would be great to indicate in the commit message when you think something is aggressive/experimental and what blocker it was trying to work around.  If you do that, then a reviewer who is considering a merge (or a later developer who is spelunking in the project history) can understand where it's coming from.  They might be in a position to have more insight on other ways to get around the specific problem.

**Pull request merged**
